"""expand projects contracts tasks and master catalogs

Revision ID: e40255180d9f
Revises: c32b8d1a4fbe
Create Date: 2026-03-14 22:25:55.126689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40255180d9f'
down_revision = 'c32b8d1a4fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_catalog_option_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=40), nullable=False),
    sa.Column('catalog_key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'module_key', 'catalog_key', 'name', name='uq_system_catalog_option_configs_owner_module_catalog_name')
    )
    with op.batch_alter_table('system_catalog_option_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_catalog_option_configs_catalog_key'), ['catalog_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_catalog_option_configs_module_key'), ['module_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_catalog_option_configs_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('responsible', sa.String(length=120), nullable=True),
    sa.Column('creator', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('estimated_duration_days', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('logged_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('task_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('assignee_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'assignee_name', name='uq_task_assignees_task_name')
    )
    with op.batch_alter_table('task_assignees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignees_task_id'), ['task_id'], unique=False)

    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_attachments_task_id'), ['task_id'], unique=False)

    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predecessor_task_id', sa.Integer(), nullable=False),
    sa.Column('successor_task_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['successor_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_task_id', 'successor_task_id', name='uq_task_dependencies_pair')
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_predecessor_task_id'), ['predecessor_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_successor_task_id'), ['successor_task_id'], unique=False)

    with op.batch_alter_table('client_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_name', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('auto_renewal', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('billing_mode', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('client_contract_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('objective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_unit', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('product_solution', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('service_module', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('complexity_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('criticality_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('project_origin', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('parent_project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_manager', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('commercial_manager', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('functional_manager', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('technical_manager', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('client_sponsor', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('key_user', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('onboarding_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('actual_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('actual_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estimated_duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kickoff_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('close_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('methodology', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('documentation_repo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_board_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('committee_frequency', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('communication_channel', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('billing_mode', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('currency_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sold_budget', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimated_margin', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('average_rate', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cost_center', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('erp_psa_code', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_client_contract_id'), ['client_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_parent_project_id'), ['parent_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_code'), ['project_code'], unique=True)
        batch_op.create_foreign_key(
            'fk_projects_parent_project_id',
            'projects',
            ['parent_project_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_projects_client_contract_id',
            'client_contracts',
            ['client_contract_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_client_contract_id', type_='foreignkey')
        batch_op.drop_constraint('fk_projects_parent_project_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_project_code'))
        batch_op.drop_index(batch_op.f('ix_projects_parent_project_id'))
        batch_op.drop_index(batch_op.f('ix_projects_client_contract_id'))
        batch_op.drop_column('erp_psa_code')
        batch_op.drop_column('cost_center')
        batch_op.drop_column('average_rate')
        batch_op.drop_column('estimated_hours')
        batch_op.drop_column('estimated_margin')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('sold_budget')
        batch_op.drop_column('currency_code')
        batch_op.drop_column('billing_mode')
        batch_op.drop_column('communication_channel')
        batch_op.drop_column('committee_frequency')
        batch_op.drop_column('external_board_url')
        batch_op.drop_column('documentation_repo')
        batch_op.drop_column('methodology')
        batch_op.drop_column('close_date')
        batch_op.drop_column('kickoff_date')
        batch_op.drop_column('estimated_duration_days')
        batch_op.drop_column('actual_end_date')
        batch_op.drop_column('actual_start_date')
        batch_op.drop_column('onboarding_date')
        batch_op.drop_column('key_user')
        batch_op.drop_column('client_sponsor')
        batch_op.drop_column('technical_manager')
        batch_op.drop_column('functional_manager')
        batch_op.drop_column('commercial_manager')
        batch_op.drop_column('project_manager')
        batch_op.drop_column('parent_project_id')
        batch_op.drop_column('project_origin')
        batch_op.drop_column('criticality_level')
        batch_op.drop_column('complexity_level')
        batch_op.drop_column('category')
        batch_op.drop_column('service_module')
        batch_op.drop_column('product_solution')
        batch_op.drop_column('business_unit')
        batch_op.drop_column('objective')
        batch_op.drop_column('client_contract_id')
        batch_op.drop_column('project_code')

    with op.batch_alter_table('client_contracts', schema=None) as batch_op:
        batch_op.drop_column('amount')
        batch_op.drop_column('currency_code')
        batch_op.drop_column('billing_mode')
        batch_op.drop_column('auto_renewal')
        batch_op.drop_column('contract_name')

    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_successor_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_predecessor_task_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))

    op.drop_table('task_comments')
    with op.batch_alter_table('task_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_attachments_task_id'))

    op.drop_table('task_attachments')
    with op.batch_alter_table('task_assignees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignees_task_id'))

    op.drop_table('task_assignees')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_task_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('system_catalog_option_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_catalog_option_configs_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_system_catalog_option_configs_module_key'))
        batch_op.drop_index(batch_op.f('ix_system_catalog_option_configs_catalog_key'))

    op.drop_table('system_catalog_option_configs')
    # ### end Alembic commands ###
